import { describe, expect, test } from '@jest/globals'

import isUsername from '../lib/is-username'

describe('validates username', () => {
  test('should checks valid username pattern', () => {
    expect(isUsername('j123')).toBeTruthy()
    expect(isUsername('jhon')).toBeTruthy()
    expect(isUsername('jack03')).toBeTruthy()
    expect(isUsername('caricati')).toBeTruthy()
    expect(isUsername('caricati.123')).toBeTruthy()
    expect(isUsername('jhon_jack')).toBeTruthy()
    expect(isUsername('stanf4rd')).toBeTruthy()
    expect(isUsername('c4r1c4t1')).toBeTruthy()
    expect(isUsername('pyr3')).toBeTruthy()
    expect(isUsername('ejs.j')).toBeTruthy()
    expect(isUsername('feeed')).toBeTruthy()
    expect(isUsername('me-too')).toBeTruthy()
  })

  test('should checks invalid username pattern', () => {
    expect(isUsername('a')).toBeFalsy()
    expect(isUsername('')).toBeFalsy()
    expect(isUsername(' ')).toBeFalsy()
    expect(isUsername('ab')).toBeFalsy()
    expect(isUsername('abc')).toBeFalsy()
    expect(isUsername('abc.')).toBeFalsy()
    expect(isUsername('abc!@#')).toBeFalsy()
    expect(isUsername('A@jack')).toBeFalsy()
    expect(isUsername('.jean.')).toBeFalsy()
    expect(isUsername('.backtop')).toBeFalsy()
    expect(isUsername('backtop.')).toBeFalsy()
    expect(isUsername('jacks-')).toBeFalsy()
    expect(isUsername('abc!')).toBeFalsy()
    expect(isUsername('abc@')).toBeFalsy()
    expect(isUsername('abc#')).toBeFalsy()
    expect(isUsername('abc$')).toBeFalsy()
    expect(isUsername('abc%')).toBeFalsy()
    expect(isUsername('abc¨')).toBeFalsy()
    expect(isUsername('abc&')).toBeFalsy()
    expect(isUsername('abc*')).toBeFalsy()
    expect(isUsername('abc(')).toBeFalsy()
    expect(isUsername('abc)')).toBeFalsy()
    expect(isUsername('abc-')).toBeFalsy()
    expect(isUsername('abc=')).toBeFalsy()
    expect(isUsername('abc+')).toBeFalsy()
    expect(isUsername('abc/')).toBeFalsy()
    expect(isUsername('abc|')).toBeFalsy()
    expect(isUsername('abc\\')).toBeFalsy()
    expect(isUsername("abc'")).toBeFalsy()
    expect(isUsername('abc"')).toBeFalsy()
  })
})
